# Generated by Django 4.2.8 on 2025-01-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('uid', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('favorite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=55)),
                ('image', models.URLField(max_length=12)),
                ('price', models.IntegerField()),
                ('sale', models.BooleanField()),
                ('description', models.CharField(max_length=55)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybooks.author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybooks.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybooks.genre')),
            ],
        ),
    ]
